sudo: required
services:
  - docker

before_install:
  - docker build -t vjthedj1990/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run vjthedj1990/react-test npm test -- --coverage

after_success:
  - docker build -t vjthedj1990/multi-client ./client
  - docker build -t vjthedj1990/multi-nginx ./nginx
  - docker build -t vjthedj1990/multi-server ./server
  - docker build -t vjthedj1990/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push vjthedj1990/multi-client
  - docker push vjthedj1990/multi-nginx
  - docker push vjthedj1990/multi-server
  - docker push vjthedj1990/multi-worker

